networks:
  Trans_Net:

services:
  api:
    container_name: api_transfer
    build: . # vai buildar com base no meu dockerfile
    depends_on:
      - banco
    ports:
      - 5000:5000
    networks:
      - Trans_Net

  banco:
    container_name: db_transfer
    image: "postgres:12.0-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - Trans_Net