networks:
  Trans_Net:

services:
  api:
    container_name: api_transfer
    build: . # vai buildar com base no meu dockerfile
    depends_on:
      - banco
    ports:
      - 5000:5000
    environment:
      - DATABASE_PORT = 5432
      - DATABASE_USER = postgres
      - DATABASE_DB = archlimpa
      - DATABASE_PASSWORD = 1234
      - DATABASE_HOST=banco
    networks:
      - Trans_Net

  banco:
    container_name: db_transfer
    image: "postgres:12.0-alpine"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - Trans_Net